"""Explicit issue briefs; generate catalog.json with build_catalog.py, never publish here."""

# Columns: readiness+difficulty | slug | title | observed gap / proposal rationale |
# acceptance criteria separated by ~ | optional existing issue number.
# R = ready, D = design needed. 1/2/3 = beginner/intermediate/advanced.
TRACKS = {
"onboarding": ("Contributor experience", "CON", "CONTRIBUTING.md README.md pyproject.toml", "docs/src/content/docs/contributing", "docs", """
R1|macos-setup|Write a clean-checkout macOS contributor walkthrough|The root guide does not walk through macOS tool installation and PATH troubleshooting|Use a fresh-directory setup with Python 3.13 and uv~Show the mocked test path without Redis or a real key~Explain resolving uv outside an interactive shell
R1|linux-setup|Write an Ubuntu contributor setup walkthrough|There is no Ubuntu-specific test-only onboarding page|Verify uv installation and repository-root commands~Separate unit-test prerequisites from live FFmpeg and Redis setup~Record the Ubuntu version used
R1|windows-setup|Write a Windows PowerShell contributor walkthrough|Existing commands assume a Unix shell|Provide PowerShell equivalents for environment variables and focused pytest~Document bash check-script alternatives~State which steps were verified on Windows
R1|wsl-setup|Document WSL2 development and filesystem placement|There is no guidance for contributors using WSL2|Explain Linux-side uv setup and repository location~Document Docker Desktop integration as optional~Include a no-cloud test smoke command
R1|first-pr-walkthrough|Add an illustrated first-PR walkthrough|The guide lists steps but does not demonstrate a fork-to-review workflow|Use a synthetic documentation change as the example~Explain upstream main versus origin and issue linking~Provide text alternatives for any screenshots
R1|focused-pytest|Explain focused pytest selection with repo examples|New contributors may rerun the whole suite for every edit|Demonstrate file, node ID, and -k selection using existing tests~Explain test collection and root-relative fixtures~Avoid adding a second test runner
R1|pylint-help|Write a guide to interpreting repository pylint failures|The check output gives codes without contributor-oriented explanations|Explain import-order exceptions in conftest and scoped suppressions~Show unused-argument and line-length fixes~Discourage disabling checks globally
R1|fixture-guide|Explain authenticated and unauthenticated test clients|The default client silently includes a fake bearer token|Show removing authorization for a negative test~Explain fake Redis lifetime and mock target paths~Use existing fixture names accurately
R1|mock-targets|Teach patching the name used by the route|Route imports require patching their local bindings|Contrast patching analyze.get_assessment with the original service symbol~Include a runnable small example~Explain avoiding real provider calls
R1|git-conflicts|Add a focused merge-conflict recovery guide|Stacked branches previously caused deployment work to miss main|Explain updating a fork and resolving conflicts without force-pushing main~Include safe backup branch commands~Explain why newcomers should branch from upstream main
R1|review-feedback|Explain how to address review feedback in one PR|There is no review-iteration walkthrough|Show making a follow-up commit and rerunning focused checks~Explain when to ask for clarification~Do not promise review turnaround times
R1|issue-reproduction|Add a guide to submitting synthetic reproductions|Bug reports need useful evidence without private scam messages|Provide a minimal curl or pytest reproduction template~Show replacing tokens and personal data~Separate observed facts from suspected causes
R1|docs-navigation|Explain where documentation pages and sidebar entries live|The docs package is separate from the Python API|Trace one guide through Astro content and sidebar configuration~Explain generated files not to commit~Include a local preview workflow
R1|dependency-changes|Document lockfile updates without unrelated upgrades|Python and npm have independent lockfiles|Show targeted uv and npm dependency workflows~Explain frozen installs and reviewing lockfile diffs~Preserve the Linux CPU PyTorch source
R1|audio-test-prereqs|Explain unit tests versus real audio checks|Whisper stubbing can make contributors mistake unit tests for decoder integration|List which checks need FFmpeg or weights~Identify existing test_audio.m4a usage~Explain costs and consent for live provider checks
R1|test-data-policy|Write a synthetic fixture contribution checklist|The repository has an audio fixture but no provenance checklist|Require ownership or compatible licensing and no personal data~Set a review process for binary size and generation recipes~Document metadata to include with new fixtures
R1|debugger-guide|Add a VS Code pytest debugging walkthrough|No repo-specific debugger instructions exist|Demonstrate breaking in a mocked text request~Keep secrets out of launch configurations~Use the uv environment interpreter
R1|minimal-pr-checklist|Document how to choose a small independent change|The roadmap includes shared-file and isolated-file work|Show a good one-outcome PR and an over-broad counterexample~Explain non-goals and references versus fixes~Include guidance for partially completed work
R1|offline-work|Document what can and cannot run offline|Tests avoid external services but package installation needs downloads|Separate first-time dependency fetches from cached execution~Describe mocked unit tests and docs builds~Do not claim uv sync works without cached packages
R1|contributor-glossary|Add a glossary for API and contribution terminology|Beginners encounter ASGI, fixtures, CORS, and upstream without definitions|Define terms using repository examples~Link to authoritative references~Distinguish upstream Git from the DeepSeek upstream
"""),
"text": ("Text and API contracts", "TXT", "app/models/request.py app/models/response.py app/api/analyze.py tests/test_security.py", "tests/roadmap/text", "pytest", """
R1|unicode-contract|Test Unicode and multiline text round-tripping|Existing text tests use short ASCII examples|Cover emoji, non-Latin text, and embedded newlines~Assert the mocked assessor receives the intended normalized body~Keep the response contract unchanged
R1|length-boundary|Test the inclusive text character boundary|Current tests reject 10001 characters but do not accept exactly 10000|Accept exactly 10000 characters and reject the next character~Distinguish Unicode character count from encoded body bytes~Make no live provider calls
R1|field-shapes|Cover missing null and structured text bodies|Current bounds tests do not cover absent or wrong-type JSON fields|Parametrize missing, null, list, and object bodies~Assert 422 without invoking the assessor~Avoid depending on full Pydantic error wording
R1|json-errors|Cover malformed JSON independently of text validation|Only valid JSON is exercised by text tests|Send truncated JSON and invalid encodings through TestClient~Assert controlled client errors and no provider calls~Document current FastAPI behavior without inventing a new envelope
R1|media-types|Characterize accepted text request media types|The contract says JSON but content-type edge cases lack tests|Cover JSON with charset, plain text, and missing media type~Assert observed framework behavior with a fake assessor~Escalate contract changes rather than silently accepting new types
R1|legacy-sender|Test legacy sender boundaries and optionality|The old issue required sender, but it is now intentionally optional|Accept body-only email requests and a 320-character sender~Reject an over-limit or structured sender~Verify sender is not forwarded into assessment|41
R1|legacy-body|Protect text and legacy email validation parity|Text bounds exist but matching legacy route cases are incomplete|Run the same empty, whitespace, and length cases against both routes~Assert no provider call for invalid bodies~Preserve the deprecated alias|63
R1|certainty-model|Test response certainty boundaries as a public contract|Field constraints exist but explicit response-model boundary tests are absent|Accept 0 and 100; reject values outside that range~Test model validation without the provider~Do not alter coercion policy in this issue|62
R1|response-reason|Test the public reason length constraint|Reason bounds were added without focused contract tests|Accept a nonempty reason at the 2000-character boundary~Reject missing, empty, and over-limit values~Use complete valid assessment payloads otherwise
R1|enum-contract|Test all documented label and score values|Current route tests exercise only a subset of valid enums|Cover all allowed labels and scores~Reject unknown enum strings~Verify schema enums and response-model validation agree
R1|health-contract|Test exact public liveness response without authentication|Existing outage test checks health status code but not the body or public access|Remove default authorization and assert health status JSON~Prove Redis and provider functions are not called~Keep liveness cheap|34
R1|method-contract|Test unsupported methods on analysis endpoints|There are no method-not-allowed regression tests|Exercise GET and PUT against POST routes with valid auth~Assert 405 and no provider invocation~Avoid conflating auth rejection with method rejection
R1|openapi-text|Test live OpenAPI text request and response metadata|Current metadata tests inspect AST and focus on email and audio|Assert /text JSON schema and response reference exist~Verify the documented bearer security requirement~Use app.openapi without network access
R1|openapi-legacy|Test deprecation metadata on the legacy email route|Deprecated=True exists but the generated schema is not asserted|Assert /email is deprecated and /text is not~Verify sender remains optional in generated schema~Do not remove the alias
R2|body-bytes-boundary|Test encoded-byte limits separately from character limits|The HTTP guard and Pydantic enforce different units|Use multibyte and escaped JSON near 64 KiB~Verify 413 occurs before provider work when encoded bytes exceed the cap~Use streamed and declared-length cases
D2|unknown-fields-policy|Decide how text requests should handle unknown fields|Pydantic currently ignores extra fields implicitly|Document compatibility impact of ignore versus forbid~Choose an explicit policy and migration approach~Implement only after maintainer approval
D2|normalization-policy|Specify treatment of invisible and normalization characters|Whitespace stripping does not define zero-width or normalization semantics|Include examples from legitimate multilingual text~Choose a policy without destructive blanket stripping~Describe validation tests before changing models
D3|versioned-contracts|Design an API contract versioning policy|Breaking auth and response changes need a repeatable compatibility process|Define versioning and deprecation windows~Cover HTTP and WebSocket envelopes~Do not add a new version merely for this document
D2|error-schema|Design typed documented error envelopes|HTTP errors currently use strings, dictionaries, and validation arrays|Inventory existing client-visible shapes~Propose compatible models and migration tests~Coordinate before changing global handlers
D2|text-idempotency|Evaluate idempotency keys for repeated text requests|Retries may cause repeated paid inference|Define request hashing, expiry, principal isolation, and mismatch errors~Assess storage and privacy costs~Do not cache raw content by default
"""),
"auth": ("Authentication and configuration", "AUT", "app/services/auth.py app/config.py app/middleware.py tests/conftest.py", "tests/roadmap/auth", "pytest", """
R2|missing-provider-key|Test startup rejection without a provider credential|Validation exists but startup failure lacks direct regression coverage|Use isolated configuration state and lifespan startup~Assert a secret-safe message for a missing key~Avoid accidentally reading a developer .env|64
R2|numeric-settings|Test invalid positive-integer environment settings|positive_int validates values but parsing errors are not covered|Cover zero, negative, noninteger, and valid values for all numeric settings~Run import-sensitive cases in isolated subprocesses~Assert no model or provider work occurs|56
R1|empty-token-list|Test empty and short backend token configuration|Startup token validation lacks focused cases|Cover empty lists, whitespace-only values, and one short token among valid tokens~Assert startup refusal without printing tokens~Keep live requests out of the test
R1|bearer-grammar|Test malformed bearer-header handling|Only missing and wrong token paths have coverage|Cover unsupported schemes, empty credentials, and mixed-case Bearer~Assert the documented WWW-Authenticate header~Keep HTTP and middleware outcomes consistent
R1|token-rotation|Test two configured tokens without leaking identity|No test demonstrates the rotation window|Accept both tokens and reject a third~Check generated identities differ without containing raw tokens~Do not change token storage architecture
R2|quota-isolation|Test token-based quotas through the HTTP boundary|Existing independent-quota test calls the Redis service directly|Give two valid principals different exhausted quota states~Assert isolation through /text with a fake provider~Do not trust caller-supplied identity headers
R1|forwarded-headers|Verify forwarded IP headers cannot change token identity|The old IP-proxy assumption no longer matches token quotas|Send spoofed Forwarded and X-Forwarded-For values with one token~Verify they do not bypass its quota~Document --no-proxy-headers in the test rationale|68
R2|cors-preflight|Test approved and rejected CORS preflight requests|CORS middleware behavior is not directly covered|Verify approved Origin, method, and Authorization-header preflight~Verify unapproved origins are not granted browser access~Do not require bearer credentials on OPTIONS preflight
R2|cors-error-responses|Test CORS headers on authenticated API failures|Browser clients need readable error responses when origins are allowed|Exercise 401, 413, and 429 for an allowed origin~Verify headers without weakening auth~Use an isolated app/config setup
R1|secret-safe-errors|Test that invalid credentials never appear in error bodies|Current auth tests assert codes but not supplied-secret absence|Use a synthetic distinctive token and assert it is not echoed~Check HTTP rejection and WebSocket handshake behavior~Avoid real secret fixtures
R2|settings-isolation|Add a reusable isolated settings-test pattern|Module-level settings make env mutation order-sensitive|Demonstrate import isolation without global sys.modules pollution~Restore environment after each case~Make the helper work without a real .env
D3|constant-time-review|Review token comparison and rotation cost bounds|The token list is scanned per request and may grow|Assess timing behavior and upper bounds for configured credentials~Document rotation-size recommendations~Do not replace authentication with unreviewed crypto
D3|credential-revocation|Design revocation behavior for open WebSockets|A connection identifies its token once before accepting messages|Define when revoked credentials stop authorizing existing sessions~Consider rolling deployments and connection lifetime~Implement only after approving the policy
D3|settings-object|Design immutable typed settings without import side effects|Environment parsing at import complicates tests and multiple app instances|Propose a settings object and app-factory integration~Preserve current env names and startup validation~Include a migration plan for direct imports
D3|token-management|Design principal IDs separate from secret token hashes|Token rotation currently changes quota identity|Specify stable client IDs, rotation, and revocation semantics~Plan compatible configuration and quota migration~Do not introduce a public account system implicitly
D3|gateway-identity|Specify trusted end-user identity forwarding|Shared backend quotas do not provide per-user quotas|Choose signed claims or verified user tokens rather than arbitrary headers~Define trust boundaries and replay limits~Keep backend tokens out of extensions
D3|redis-credentials|Review Redis TLS and authentication configuration|Managed Redis may require passwords or users beyond a TLS URL|Document supported redis-py URL behavior and secret-safe errors~Test with isolated TLS fixtures before cloud rollout~Avoid embedding secrets in logs or Terraform output
D3|request-id-trust|Design safe incoming request-ID handling|Correlation identifiers need input bounds and trust rules|Define generated versus accepted IDs and maximum length~Prevent control characters and high-cardinality misuse~Coordinate with observability proposals
D3|config-secret-audit|Audit configuration exposure through diagnostics|Future diagnostics must not reveal runtime credentials|Inventory startup errors, health responses, and logging surfaces~Define redaction rules for URLs and exception chains~Use synthetic secrets in validation
D3|key-strength-policy|Evaluate stronger server-token configuration checks|A 32-character minimum does not guarantee entropy|Document random generation and placeholder rejection options~Evaluate compatibility and false assurances~Do not claim length validation proves randomness
"""),
"audio": ("Audio ingestion and transcription", "AUD", "app/api/analyze.py app/services/transcription.py tests/test_main.py tests/test_transcription.py", "tests/roadmap/audio", "pytest", """
R1|empty-upload|Test empty and missing audio uploads distinctly|Existing unsupported-format test uses a nonempty text file|Assert controlled responses for missing file and zero bytes~Verify no transcription or provider call~Keep validation ordering explicit
R1|filename-spoofing|Test byte-based validation despite misleading filenames|The implementation detects bytes but this guarantee lacks tests|Use valid fixture bytes with a text extension and invalid bytes with an audio extension~Assert the outcome follows detected bytes~Keep supplied names out of temporary paths
R1|size-inclusive|Test the exact inclusive audio upload limit|Current tests cover only an oversized payload|Patch a small limit and use valid mocked format detection~Accept exactly the limit and reject the next byte~Verify transcription is skipped on rejection
R1|multipart-field|Test incorrect multipart field names|Only the expected file field is exercised|Send an upload under an incorrect field and assert validation failure~Ensure no transcription occurs~Do not change the multipart API
R2|multiple-files|Characterize repeated file parts in multipart uploads|Framework selection behavior is currently implicit|Test repeated file fields and extra fields~Record which file is analyzed and ensure unused handles close~Request a design decision before changing acceptance policy
R1|decode-error|Test subprocess failure mapping for corrupted audio|Decoder timeout is covered but CalledProcessError is not|Mock FFmpeg failure and assert InvalidAudio plus HTTP 422~Ensure stderr and local paths are not returned~Verify upload cleanup
R1|empty-transcript|Test empty and non-string transcription output|Transcription rejects empty text but no focused tests exercise it|Cover empty string, whitespace, and invalid result type~Assert InvalidAudio and no assessment call~Mock the model and subprocess
R1|duration-inclusive|Test audio exactly at the duration limit|Current test only proves over-limit rejection|Generate a tiny WAV at and just above a patched boundary~Verify exact-boundary inference and rejection before inference above it~Avoid downloading model weights
R2|decode-protocols|Protect FFmpeg network-protocol restrictions|The command uses a whitelist with no contract test|Assert network protocols are excluded from the launched command~Include a local malicious-reference fixture in opt-in integration tests~Never contact external URLs during unit tests
R2|model-load-race|Test concurrent lazy model initialization|load_model has a lock but concurrency behavior is untested|Start concurrent callers with a blocked fake loader~Assert a single load and shared model result~Avoid sleep-based flaky synchronization
R2|load-recovery|Test recovery after Whisper model initialization fails|A failed first load should not poison the singleton|Make the fake loader fail once then succeed~Assert no partially initialized model is reused~Restore module state after the test
R1|assessment-cleanup|Test audio cleanup when assessment fails after transcription|Existing cleanup test fails during transcription only|Let transcription succeed and make assessment fail~Assert temporary directory removal and slot availability~Check the controlled provider error response
R2|metadata-registry|Move audio format metadata into one documented registry|Allowed MIME values and error wording can drift|Keep supported MIME values, display names, and extensions in one source~Preserve HTTP and WebSocket behavior~Test error text derives from the registry|57
D2|decoder-availability|Define startup/readiness behavior when FFmpeg is missing|FileNotFoundError is not treated like a decode error|Choose text-only versus audio-required startup behavior~Return a controlled unavailable response where appropriate~Avoid running heavyweight decoding on each probe
D3|audio-work-budget|Design a total inference time budget|Decoder duration is bounded but model inference has no wall-clock cancellation|Evaluate process isolation rather than pretending thread cancellation kills inference~Define cleanup and capacity recovery~Keep normal text traffic responsive
D3|duration-probe|Evaluate preflight duration probing with strict limits|Current decode truncates at limit plus one second before duration inspection|Compare bounded decode against ffprobe attack surface and latency~Use malformed and misleading-duration samples~Adopt only with measurable benefit
D2|language-option|Evaluate an optional transcription language hint|Automatic language detection may be slow or inaccurate for short clips|Define allowed values and backwards-compatible request shape~Measure against synthetic multilingual fixtures~Do not silently force English
D3|audio-budget-admission|Design upload admission before expensive parsing|Token validity is checked early but quota and audio capacity come later|Identify safe body-parser and dependency boundaries~Specify rejection and accounting semantics~Include slow-client and concurrent-upload tests
D2|ffmpeg-upgrade-matrix|Plan compatibility checks for FFmpeg security updates|The image inherits a distribution FFmpeg version|Define a small licensed format matrix and supported upgrade process~Record version and decode outcomes~Avoid checking large binaries into Git
D3|transcription-backend|Evaluate alternative transcription backends behind a contract|Whisper is currently the only runtime implementation|Compare resource use, privacy, licensing, and quality on a fixed corpus~Define capability differences before abstraction~Do not replace the default without review
"""),
"websocket": ("WebSocket lifecycle", "WSS", "app/api/analyze.py app/services/auth.py scripts/serve.sh tests/test_security.py", "tests/roadmap/websocket", "pytest", """
R1|recoverable-error|Test valid audio after a recoverable WebSocket validation error|Existing tests stop after the first invalid clip|Send invalid bytes then a valid mocked clip on one connection~Assert error followed by the documented assessment~Keep the connection open for recoverable validation|44
R1|real-response-schema|Replace misleading WebSocket success fixtures with real model values|test1 uses spam and numeric score values that violate the public model|Assert exact valid label, score, certainty, and reason on WebSocket success~Use a real riskAssessment object rather than arbitrary MagicMock output~Give the test a descriptive name
R2|redis-outage|Test Redis outage on a WebSocket message|HTTP failure is covered but the socket failure path is not|Inject a Redis connection error after handshake~Assert a sanitized error and close code 1013~Verify transcription does not run|51
R2|provider-failure|Test malformed-provider failure over WebSocket|Provider service tests do not verify socket delivery of errors|Use AssessmentUnavailable at the route boundary~Assert no partial success result and a controlled error~Prove a recoverable later clip can be processed|60
R1|invalid-token|Test a wrong WebSocket bearer token|The socket auth test currently only omits the header|Supply a synthetic wrong token and assert handshake rejection~Assert no Redis or transcription work~Do not rely on a browser-visible close event before acceptance
R2|approved-origin|Test an approved WebSocket Origin header|Only rejection of an unapproved origin is covered|Configure an isolated allowed origin and connect successfully~Verify a near-match origin is rejected~Keep the origin check separate from token validation
R1|query-token|Test that URL tokens do not authorize WebSocket access|Docs forbid query-string secrets but no negative test protects this|Put a valid test token in the query without a header~Assert rejection and no analysis~Do not include real credentials in test URLs
R2|idle-timeout|Test idle socket closure without a 60-second sleep|The timeout path is not exercised by tests|Use a controllable clock or patched awaitable~Assert close code and reason~Avoid monkeypatching asyncio globally across unrelated tests
R2|busy-close|Test socket behavior when the audio slot is occupied|Busy behavior is tested at the function boundary only|Occupy the slot and send a valid clip~Assert busy error and close code 1013~Release capacity deterministically in cleanup
R2|sequential-clips|Test independent results for sequential clips|One connection should not reuse the previous transcript or assessment|Send two clips with distinct fake transcripts and results~Assert ordered matching responses~Keep every provider call mocked
R2|decode-failure|Test recoverable decoder failure over WebSocket|HTTP tests and unit decode tests do not prove socket recovery|Make one transcript raise InvalidAudio then succeed~Assert a controlled error and later result~Verify temporary files are removed
R2|disconnect-capacity|Test client disconnect while a worker thread is active|Closing a socket does not cancel asyncio.to_thread work|Use synchronization events to control the fake decoder~Ensure the slot remains held until work finishes and is then released~Avoid falsely claiming immediate cancellation
R2|socket-empty-frame|Test an empty binary frame without closing a healthy connection|Empty clips are not independently covered on the socket|Send an empty frame and assert format error~Follow with a valid clip and response~Avoid starting Whisper
R2|frame-size-integration|Add an opt-in real-Uvicorn over-limit frame check|ASGI TestClient bypasses transport-level WebSocket limits|Launch Uvicorn with a small configured ws-max-size~Assert transport close code 1009 before inference~Keep the check local and model-free
R2|transport-compression|Verify deployed WebSockets do not negotiate compression|serve.sh disables compression but no transport test asserts negotiation|Use a real local WebSocket client and configured server~Assert no permessage-deflate extension~Keep this outside fast unit tests if startup is costly
D3|unexpected-failure|Design sanitized unexpected WebSocket error handling|Only known exceptions are handled in the loop|Define logging, error envelope, and close code for unexpected failures~Preserve disconnect and cancellation semantics~Never send exception strings to clients|12
D3|stream-framing|Decide whether continuous audio streaming is a separate protocol|Current /ws intentionally accepts complete independently decodable clips|Write an ADR comparing clip mode and framed streaming~Define versioning, buffering, limits, and consent if approved~Do not break the existing endpoint|13
D3|connection-quota|Design per-principal WebSocket connection limits|Idle connections authenticate without consuming message quota|Define distributed limits, leases, disconnect cleanup, and outages~Consider several worker processes~Avoid unbounded Redis keys
D3|server-drain|Define graceful WebSocket draining during deployments|Rolling restarts can interrupt long-running audio work|Specify admission stop, in-flight grace period, and retry guidance~Align Uvicorn, ECS, and ALB timeouts~Do not promise delivery exactly once
D2|socket-errors-contract|Document and version machine-readable socket error codes|Current messages use human-readable error strings|Propose additive codes and backwards compatibility~Map validation, capacity, provider, and dependency errors~Coordinate with client maintainers before implementation
"""),
"privacy": ("Privacy filtering", "PRI", "app/services/filter.py app/services/ai.py docs/src/content/docs/guides/privacy.md", "tests/roadmap/privacy", "pytest", """
R1|baseline-redaction|Add baseline mixed-content privacy-filter regression tests|filter_sensitive has no dedicated regression suite|Cover email, phone, card-like, SSN, and long-number replacement~Use only synthetic values and assert originals disappear~Include mixed content without assuming a new pattern policy|69
R1|email-punctuation|Test email redaction beside punctuation and aliases|The current regex has boundaries that need contract coverage|Include plus aliases, subdomains, case variants, and trailing punctuation~Assert surrounding prose survives~Document unsupported syntax rather than expanding scope
R1|filter-idempotence|Test repeated filtering of already-redacted text|Client or provider layers could accidentally filter twice|Assert one and two passes agree on synthetic mixed input~Keep placeholders intact~Report counterexamples instead of adding ad hoc replacements
R1|multiline-filter|Test redaction across line breaks and repeated values|Only inline regex behavior is apparent from source|Cover several sensitive values on different lines~Assert no newline loss or input mutation~Use literal expected redacted outputs
R1|safe-prose|Add negative examples that should retain ordinary prose|Over-redaction can hide useful scam context|Use benign synthetic sentences without identifiers~Assert exact preservation~Keep disputes about numeric sequences as separate design cases
R2|regex-performance|Benchmark filtering on adversarial bounded text|Regex patterns have no performance regression corpus|Use maximum-length repeated punctuation and digits~Record environment and scaling trend rather than a fragile tiny timing threshold~Make benchmarks opt-in
D2|phone-regions|Define international phone-number redaction coverage|The phone regex is not a universal phone parser|Propose supported regions and representative synthetic examples~Assess false positives and library costs~Document limits without claiming universal anonymization
D2|card-detection|Evaluate card-like redaction and Luhn tradeoffs|Current matching treats broad digit sequences as cards|Compare false positives and missed sensitive values on synthetic data~Decide whether invalid-checksum numbers still require redaction~Preserve privacy by default
D2|ssn-precedence|Review precedence between phone SSN and generic-number patterns|Earlier substitutions can change the placeholder category|Define whether placeholder categories are meaningful to consumers~Test overlapping synthetic identifiers~Avoid changing output tokens without an approved policy
D2|iban|Propose IBAN redaction with synthetic country examples|IBAN letters and digits are not explicitly recognized|Define supported syntax and whitespace normalization~Evaluate false positives and checksum handling~Add patterns only after policy review
D2|ipv4|Decide whether IPv4 addresses should be filtered|Some scam evidence depends on network indicators|Compare privacy exposure against assessment usefulness~Specify private/public and malformed-address behavior~Avoid blanket regex changes without a decision
D2|ipv6|Decide whether IPv6 addresses should be filtered|IPv6 variants are not explicitly handled|Include compressed and bracketed synthetic forms~Evaluate identifier versus infrastructure evidence~Align with the IP-redaction policy
D3|secret-patterns|Design redaction for common secret-token shapes|Passwords and API keys may remain after numeric filtering|Limit initial supported patterns and false-positive handling~Never collect real credentials for fixtures~Document that arbitrary secrets cannot be guaranteed removed
D3|url-parameters|Evaluate sensitive URL query-parameter redaction|Phishing URLs may carry personal identifiers and useful evidence|Define parameter policy and preserve enough domain/path context~Consider encoded values and repeated parameters~Do not fetch submitted URLs
D2|unicode-digits|Review Unicode digit behavior in redaction patterns|Some regexes use Unicode-aware digit classes while email matching is ASCII|Document current behavior with synthetic scripts~Choose a consistent policy without damaging natural language~Test normalization effects explicitly
D3|replacement-collisions|Design behavior for user-authored redaction placeholders|A sender can already include strings such as [EMAIL]|Assess whether markers need provenance or escaping~Avoid exposing original identifiers in metadata~Coordinate with provider prompt changes
D3|redaction-config|Evaluate configurable redaction profiles|Different clients may require different privacy policies|Specify safe defaults and who may select profiles~Prevent untrusted users disabling protections silently~Include profile-version reporting without content logging
D3|redaction-metrics|Design aggregate redaction metrics without content leakage|Operators cannot currently measure filtering behavior safely|Use bounded category counters without identifier labels~Define retention and cardinality limits~Do not log before/after strings
D3|retention-inventory|Audit content lifetime across memory temp files logs and providers|Documentation describes flow but does not map every retention surface|Inventory normal failures disconnects and container termination~Distinguish deletion guarantees from best effort~Record provider-policy dependencies explicitly
D3|sensitive-fixture-review|Design a fixture scanning and exception process|New contributions could accidentally include real identifiers or recordings|Choose local deterministic scans and a manual review checklist~Avoid uploading fixtures to external scanners~Define safe handling of intentionally synthetic identifiers
"""),
"provider": ("Provider integration", "AI", "app/services/ai.py app/services/risk.py app/config.py tests/test_ai.py tests/test_risk.py", "tests/roadmap/provider", "pytest", """
R1|client-timeouts|Protect explicit provider timeouts and disabled SDK retries|Timeouts exist but client construction arguments lack regression coverage|Patch OpenAI construction and inspect finite timeout and max_retries=0~Prove no secret value is printed~Use a cache-reset fixture|66
R1|empty-content|Test provider choices with empty or null content|ask_deepseek may return None before response validation|Cover empty and null message content with fake choices~Assert bounded retries then AssessmentUnavailable~Never return a successful null assessment
R1|json-root-types|Test JSON arrays scalars and null from the provider|JSON parsing can succeed with a non-object root|Return each wrong root type through ask_deepseek mocking~Assert model validation controls the failure~Keep retry count bounded
R1|missing-fields|Test incomplete provider assessment objects|Existing invalid response covers only one bad label|Omit each required field in complete synthetic payloads~Assert rejection and bounded recovery~Do not weaken response requirements
R1|sdk-error-types|Test sanitized SDK authentication and rate-limit failures|Only APIConnectionError has dedicated provider coverage|Construct mocked SDK errors with synthetic messages~Assert AssessmentUnavailable without extra attempts~Verify public HTTP responses hide provider details
R1|retry-success|Test recovery when malformed JSON is followed by valid output|The suite tests invalid schema recovery but not JSON parsing recovery|Return malformed content then a complete valid assessment~Assert exactly two calls and valid final result~Use fake client output
R1|redaction-boundary|Test that only filtered content enters provider user messages|Existing test covers one email address only|Use mixed synthetic sensitive values in one request~Inspect outgoing user content and stable system content~Assert originals never enter the mocked request
R1|output-token-limit|Protect the provider response-token budget|max_tokens=1024 is not asserted by tests|Verify a bounded positive output budget in the client request~Assert JSON response format is requested~Avoid snapshotting the entire prompt text
R2|empty-choices|Handle an upstream response with no choices|ask_deepseek indexes choices[0] without an explicit guard|Reproduce with a fake SDK response~Return a controlled provider failure rather than IndexError~Add HTTP and service-boundary coverage
R2|refusal-output|Define handling of model refusals and content-filtered output|Nonstandard upstream refusal shapes can bypass normal content assumptions|Use documented SDK response fixtures~Fail closed as unavailable rather than Safe~Keep exception messages secret-safe
D2|provider-model-config|Make model selection explicit after defining validation policy|The model name is currently embedded in ai.py|Define an allowlist or operator-controlled setting and defaults~Document compatibility of response-format features~Avoid accepting arbitrary model names from clients
D2|provider-base-url|Evaluate a configurable compatible provider URL|The DeepSeek URL is hard-coded while client compatibility is implicit|Define operator-only URL validation and trust boundaries~Keep secrets scoped to approved hosts~Do not allow request-level upstream URLs
D3|total-deadline|Design a total assessment deadline across attempts|SDK per-operation timeout is not a whole-request deadline|Specify retries and timeout accounting with a monotonic clock~Consider disconnects and synchronous execution~Do not claim cancelling a waiting future stops network work
D3|circuit-breaker|Evaluate provider circuit breaking during sustained outages|Each authorized request currently attempts the failing provider|Define state, cooldown, principal fairness, and observability~Compare process-local versus shared coordination~Keep defaults simple until load evidence supports this
D3|retry-policy|Review transient-provider retry policy against cost budgets|SDK retries are disabled and schema retries are bounded|Define which errors warrant retries and who owns them~Prevent multiplication across API bot gateway and workers~Respect provider retry hints and a total deadline
D3|provider-capacity|Design bounded text-inference concurrency|Audio is serialized but text provider calls share the general thread pool|Define admission limits and overload responses~Consider quotas across processes~Benchmark without paid network calls first
D3|usage-accounting|Design privacy-safe provider usage accounting|Responses may include token usage but it is not exposed to operations|Define aggregate counters and error handling for missing usage~Never label metrics with prompts or tokens~Document estimates versus billed amounts
D2|prompt-versioning|Version assessment prompt changes and evaluation evidence|Prompt edits can alter behavior without API schema changes|Record prompt version and evaluation provenance~Define rollback and review requirements~Avoid storing private submitted content
D3|provider-failover|Evaluate provider failover without silent data-policy changes|A backup provider would receive user content under different policies|Require explicit operator configuration and user-disclosure review~Define output compatibility and cost limits~Do not automatically reroute private content
D3|provider-schema-mode|Evaluate strict structured-output support before adopting it|The current client requests generic JSON objects|Verify actual provider support and fallback behavior~Compare schema validation guarantees and latency~Keep local output validation regardless of provider mode
"""),
"quality": ("Scam-assessment evaluation", "EVAL", "app/services/ai.py app/services/filter.py app/models/response.py docs/src/content/docs/guides/privacy.md", "evaluations", "evaluation", """
D3|redaction-effect|Evaluate whether placeholders distort scam assessments|An existing issue questions the effect of privacy placeholders|Design paired synthetic raw/redacted examples without real personal data~Report false positives and false negatives separately~Require explicit opt-in for paid evaluation|6
D2|offline-harness|Design an offline evaluation runner with replayed responses|The repository has unit tests but no model-quality evaluation harness|Specify corpus and result formats plus deterministic mock mode~Separate live evaluation from normal pytest~Do not treat replay accuracy as live-model accuracy
D2|corpus-schema|Define a versioned synthetic evaluation-case schema|Comparable evaluations need consistent annotations|Include scenario, expected risk rationale, language, and provenance~Distinguish labels from subjective judgments~Provide validation independent of paid inference
D2|annotation-guide|Write an annotation rubric for scam-risk examples|Expected labels need an agreed human interpretation|Define Scam, Scam Likely, and Safe using synthetic examples~Allow ambiguous or disputed cases~Avoid presenting labels as legal findings
D2|corpus-license|Define provenance and licensing requirements for evaluation data|Contributors may be tempted to paste real scam messages|Require synthetic or explicitly licensed material~Track authorship and consent where relevant~Exclude private recordings and account details
D2|metrics-definition|Define evaluation metrics beyond overall accuracy|A single score can hide harmful false reassurance|Specify per-class precision recall and confusion matrices~Report sample counts and uncertainty~Do not use certainty as a calibrated probability
D2|class-imbalance|Design an evaluation split resistant to class imbalance|Balanced examples may not reflect real submissions|Document synthetic sampling assumptions and per-class reporting~Avoid leaking duplicate templates across splits~Keep benchmarking claims proportional to data quality
D2|paired-regressions|Design paired benign and scam scenario cases|Keyword matching can confuse normal requests with scams|Vary one meaningful cue per synthetic pair~Record why the expected outcome differs~Prevent memorized superficial phrase benchmarks
D2|phishing-scenarios|Propose a bounded synthetic phishing evaluation set|There is no documented quality corpus for credential phishing|Include benign password-reset lookalikes and malicious urgency cues~Use reserved example domains only~Submit data after the corpus schema is approved
D2|prize-scenarios|Propose advance-fee and prize scam evaluation cases|Prize language appears in examples but lacks balanced evaluation|Include upfront-fee indicators and benign prize announcements~Avoid real company impersonation data~Use the approved corpus schema
D2|support-scenarios|Propose technical-support scam evaluation cases|Support scams need different cues from prize scams|Include unsolicited remote-access requests and benign support interactions~Document ambiguity rather than forcing all examples to Scam~Use synthetic identifiers
D2|investment-scenarios|Propose investment-fraud evaluation cases|Financial certainty claims need domain-specific examples|Include guaranteed-return claims and benign financial education~Avoid giving investment recommendations~Record reviewer rationale for expected labels
D2|marketplace-scenarios|Propose marketplace scam evaluation cases|Off-platform payment and shipping stories need contrast cases|Include synthetic buyer and seller conversations~Preserve context needed to distinguish normal transactions~Do not scrape private marketplaces
D2|impersonation-scenarios|Propose impersonation and emergency-payment evaluation cases|Short impersonation messages can resemble genuine emergencies|Include benign urgent requests as controls~Use fictional people and organizations~Document uncertainty and missing context
D2|multilingual-plan|Define multilingual evaluation coverage and review ownership|Supporting Unicode does not establish assessment quality in each language|Select a small initial language set with qualified reviewers~Report results per language~Do not bulk-machine-translate a benchmark and claim coverage
D3|injection-evaluation|Design prompt-injection resistance evaluation|Separating user content from system text is not a complete defense|Use synthetic instruction-overriding and output-format attacks~Define measurable failures without publishing private prompts~Keep this separate from normal scam classification scoring
D2|audio-text-parity|Design evaluation of transcription-induced classification drift|A correct text assessment may degrade after transcription errors|Pair licensed synthetic audio with reference transcripts~Separate transcription error from classifier error~Record model and hardware versions
D2|confidence-study|Evaluate how certainty relates to observed correctness|The integer certainty field is explicitly uncalibrated|Specify calibration plots and minimum sample caveats~Avoid converting it into a probability without evidence~Keep findings advisory
D2|evaluation-report|Design a reproducible model-change report template|Prompt and model upgrades need comparable evidence|Include dataset version settings costs and limitations~Report regressions rather than only average improvements~Support offline report generation
D3|release-quality-gate|Decide whether model-quality checks should gate releases|Paid and stochastic evaluations are unsuitable as naive PR blockers|Define which offline regressions are deterministic enough for CI~Separate scheduled live checks and human review~Set no numerical threshold without baseline evidence
"""),
"observability": ("Operations and observability", "OBS", "app/main.py app/services/risk.py app/services/rate_limit.py scripts/serve.sh", "docs/decisions/observability", "decision", """
D3|http-unexpected-errors|Design a sanitized fallback for unexpected HTTP failures|Known failures are handled but no application-wide fallback policy exists|Specify stable public responses and private diagnostic fields~Preserve FastAPI validation and HTTPException behavior~Test secrets and payloads cannot leak|72
D2|structured-logging|Define a content-free structured logging schema|Runtime prints were removed but no operational event schema exists|Choose bounded fields for route status duration and error category~Exclude raw URLs with credentials and request content~Document levels and sampling
D2|request-correlation|Design end-to-end request correlation|Operators cannot trace one failure across gateway API and provider boundary|Define generated IDs and response headers~Validate untrusted incoming identifiers~Avoid treating correlation IDs as authorization
D3|metrics-export|Choose a metrics export approach suitable for ECS|There is no application metrics integration|Compare CloudWatch EMF OpenTelemetry and Prometheus costs~Define bounded label sets~Avoid requiring a public metrics endpoint
D2|latency-histograms|Specify endpoint latency measurements|Averages hide slow audio and provider requests|Define monotonic timings and buckets per operation~Separate decoding transcription and upstream latency~Exclude model content from labels
D2|quota-metrics|Specify rate-limit and Redis failure metrics|429 and 503 currently lack aggregate operational visibility|Count allowed denied and unavailable outcomes~Bound principal cardinality through aggregation~Do not emit token hashes as public labels
D2|audio-capacity-metrics|Specify audio-slot utilization and rejection metrics|A serialized worker needs capacity visibility|Measure busy rejections and active duration~Account for disconnects without double counting~Keep instrumentation nonblocking
D3|provider-spend-metrics|Design spend estimates and billing reconciliation|Model usage can cost money even for failed requests|Separate token estimates from billed amounts~Define provider-specific price configuration and update responsibility~Never log request text to estimate cost
D2|redis-latency|Specify Redis timing and error categories|Readiness detects outages but not sustained dependency latency|Distinguish connect timeout command timeout and server errors~Avoid excessive ping traffic~Use aggregate histograms
D2|health-probe-policy|Document and test readiness dependency boundaries|The old readiness issue is implemented but acceptance needs a precise contract|Verify Redis readiness and configuration startup validation~Document that probes do not call DeepSeek or transcribe~Test failures without paid checks|71
D2|cloudwatch-dashboard|Design a minimal CloudWatch dashboard for the API|Deployment docs list metrics but supply no dashboard artifact|Include task health HTTP errors latency and quota denials where available~Use placeholders for resource identifiers~Document prerequisites rather than inventing nonexistent metrics
D2|alarm-policy|Define actionable error and latency alarms|Alert thresholds need workload-specific baselines|Separate immediate outage alerts from trend warnings~Include runbook links and evaluation windows~Avoid hard-coded production thresholds without evidence
D2|redis-runbook|Write a Redis outage and saturation runbook|Fail-closed behavior needs operator recovery guidance|Explain 503 diagnosis TTL resets and safe recovery~Avoid flushing production keys as a default fix~Use read-only diagnostic commands first
D2|provider-runbook|Write a provider outage and credential-failure runbook|502 can originate from several provider failures|Distinguish credential budget network and invalid-output cases~Describe safe tests without exposing secrets~Explain when not to retry
D2|audio-runbook|Write an audio-busy and slow-inference runbook|CPU inference may hold the single slot for a long time|Explain capacity limits and hardware measurements~Separate decoder timeout from model runtime~Avoid recommending extra workers without memory sizing
D2|memory-runbook|Write an out-of-memory investigation runbook|Model and upload memory can cause task restarts|Describe ECS exit evidence and baseline measurement~Include tmpfs and model-cache distinctions~Do not capture private input in diagnostics
D3|trace-privacy|Design opt-in tracing with privacy-safe attributes|Automatic HTTP instrumentation can capture sensitive metadata|Define excluded headers bodies and URLs~Specify sampling and retention~Verify synthetic secrets are removed before export
D2|logging-retention|Define log retention and access policy examples|Cloud logging defaults may retain data longer than expected|Provide ECS-friendly retention settings and least-privilege examples~Explain sensitive incident handling~Avoid claiming logs contain no secrets without tests
D3|slo-design|Define initial service-level objectives from measured behavior|No traffic or latency baseline supports production SLO claims|Separate text audio and readiness objectives~Specify measurement windows and exclusions~Treat numerical targets as proposals pending benchmarks
D2|incident-template|Create a lightweight operational incident template|There is no repeatable way to record outages and lessons|Include impact timeline detection recovery and follow-up owners~Exclude personal submitted content~Use a fictional worked example
"""),
"clients": ("Client integrations and examples", "CLI", "docs/src/content/docs/reference/text.md docs/src/content/docs/reference/audio.md app/models/response.py", "examples", "example", """
R1|python-text|Add a standalone synchronous Python text example|The README only provides curl|Read base URL and token from environment~Call /text with a finite timeout and handle non-2xx safely~Document dependencies and fake-server verification
R1|python-async|Add an asynchronous Python text example|Async bot authors lack an example|Reuse one async client and set timeouts~Keep credentials server-side~Provide a model-free mock transport test
R1|node-text|Add a Node fetch text example|There is no JavaScript backend example|Use environment variables and AbortSignal timeout~Validate HTTP status before consuming a result~Never print the token
R1|python-audio|Add a bounded Python multipart audio example|Audio clients need correct file-field and error handling|Use multipart field file and a file context manager~Handle 413 415 422 and 503 distinctly~Document local file limits before upload
R1|node-audio|Add a Node multipart audio example|Node callers lack a documented file upload path|Send the file field with supported runtime APIs~Bound client timeout and validate response shape~Use synthetic or licensed files only
R1|python-websocket|Add a backend Python clip WebSocket example|Docs explain the protocol without an executable client|Send Authorization in the handshake and one complete clip at a time~Handle error messages and close codes~Do not use query-string credentials
R1|node-websocket|Add a backend Node clip WebSocket example|Browser and Node WebSocket capabilities are easily confused|Use a library supporting server-side handshake headers~Explain why it is not browser-extension code~Handle sequential clips and shutdown
R1|python-retry-helper|Add an isolated bounded Retry-After example for Python|Clients may retry expensive requests aggressively|Parse delta seconds and cap attempts plus total delay~Use jitter and a fake clock in tests~Explain non-idempotent request costs
R1|node-retry-helper|Add an isolated bounded Retry-After example for Node|No JavaScript guidance demonstrates controlled retries|Handle malformed retry hints and cap delays~Test with a local fake response source~Do not retry authentication or validation errors
R1|typescript-contract|Publish hand-written TypeScript assessment types with fixtures|Response examples lack reusable client-side types|Match documented enums certainty and reason~Include a runtime guard or clearly state types alone do not validate~Verify using synthetic valid and invalid fixtures
R1|python-response-validation|Add client-side Pydantic response validation example|A remote API response should not be blindly trusted by clients|Use the documented enums and numerical bounds~Keep example models independent of server internals~Demonstrate invalid-response handling
R1|bruno-collection|Add a secret-free Bruno API collection|Contributors lack a reusable local API request collection|Cover health readiness text and audio with environment placeholders~Exclude real credentials and private uploads~Document importing and choosing local base URL
R1|postman-collection|Add a secret-free Postman collection|Some first-time users prefer a GUI API client|Use collection variables for base URL and backend token~Cover success and error examples~Ensure exported files contain no credentials
R2|discord-slash|Add a small Discord text slash-command example|The docs describe architecture but not deferred interaction handling|Use backend-only credentials and a finite API timeout~Return advisory results without posting input publicly~Test API behavior with a fake transport
R2|discord-context|Add a Discord message-context analysis example|Users should explicitly choose which message to submit|Describe required permissions and consent flow~Avoid scanning all channel messages~Mock Discord and ScamShield boundaries in tests
D3|discord-quotas|Design per-user and per-guild bot quotas|One backend token shares a single API quota|Derive identity from verified Discord events~Specify fairness and retry behavior~Do not trust arbitrary IDs in a public endpoint
D3|extension-gateway|Design a user-authenticated browser-extension gateway|The API supports service tokens rather than end-user sessions|Define identity verification quotas and allowed-origin policy~Keep shared secrets entirely server-side~Choose an existing identity provider before implementation
D2|extension-ui|Design an explicit-consent selected-text extension UI|Browser examples must not encourage background data collection|Show what will be submitted and where it goes~Define accessibility and minimal permissions~Depend on an approved gateway contract
D2|client-error-guide|Define a reusable cross-language client error taxonomy|Clients need consistent distinctions between retryable and permanent failures|Map existing HTTP statuses and WebSocket codes~Preserve raw details only in secret-safe diagnostics~Document advisory-result versus failed-analysis states
D2|client-compatibility|Design an example compatibility check against OpenAPI|Examples can drift after response-model changes|Choose a lightweight local mock or schema-based check~Avoid a new published SDK before ownership is agreed~Keep paid provider calls out of CI
"""),
"docs": ("Documentation and accessibility", "DOC", "docs/astro.config.mjs docs/src/content/docs/reference/text.md docs/src/content/docs/guides/deployment.md example.env", "docs/src/content/docs/guides/roadmap", "docs", """
R1|environment-reference|Create a complete environment-variable reference table|The example file and deployment page scatter configuration semantics|List all current env names units defaults requiredness and restart behavior~Explain singular client token versus plural server token list~Cross-check values against config.py and serve.sh|36
R1|text-flow|Add a text request data-flow diagram|The docs have no visual route-to-provider explanation|Show auth body limits quota filtering assessment and response validation~Include a text alternative~Avoid implying redaction is complete anonymization
R1|audio-flow|Add an audio processing and cleanup diagram|Several temporary and model stages are described only in prose|Show upload decode duration validation transcription and provider call~Mark local versus external processing~Include failure cleanup paths
R1|websocket-sequence|Add a complete-clip WebSocket sequence diagram|Readers may interpret /ws as continuous streaming|Show handshake auth binary clip response and close behavior~Include invalid-clip recovery and a text alternative~Do not invent framing headers
R1|error-examples|Add exact synthetic examples of each HTTP error envelope|The error reference describes shapes but few concrete examples|Use observed FastAPI string dictionary and validation-array forms~Explain which details are stable contracts~Do not include traceback screenshots
R1|cors-explainer|Explain browser CORS versus service authentication|New contributors often assume CORS protects secrets|Contrast browser origin enforcement with backend bearer authentication~Explain preflight and why wildcards are rejected~Link to extension gateway guidance
R1|quota-explainer|Illustrate the fixed-window token quota|Readers may assume quotas are per IP or per user|Draw requests around window boundaries~Explain shared HTTP and socket usage and Redis restart reset~Use current defaults with configurable caveats
R1|whisper-model-guide|Explain choosing a Whisper model for local experiments|Only the default turbo model is discussed|Describe memory latency and language tradeoffs without fabricated benchmarks~Show WHISPER_MODEL configuration~Explain keeping live evaluation separate from unit tests
R1|audio-formats-guide|Explain containers codecs and complete clips|A supported extension alone does not guarantee decodable audio|Differentiate byte detection from FFmpeg decoding~Explain misleading filenames and complete WebM segments~Link to existing limits rather than duplicate constants
R1|privacy-faq|Add a plain-language privacy FAQ|The privacy guide is technically accurate but lacks user-facing questions|Explain whether audio text and transcripts leave the host~State retention limits and best-effort filtering clearly~Avoid provider-policy guarantees not verified for the account
R1|advisory-results|Explain how clients should display risk assessments|Users can mistake Safe and certainty for guarantees|Show neutral advisory wording and failure states~Distinguish ordinal score from numerical certainty~Avoid unsupported claims of detection accuracy
R1|ecs-vs-compose|Explain deployment artifacts and their supported roles|Compose is implemented while ECS setup is largely guidance|List what the repo actually ships versus operator-owned AWS setup~Explain cache and writable-storage needs~Do not present future Terraform as available
R1|tls-troubleshooting|Add TLS and DNS troubleshooting for the documented proxy|Certificate and DNS errors can be mistaken for API failures|Use read-only checks for DNS certificate and local readiness~Distinguish public proxy from loopback API~Avoid recommending disabling TLS verification
R1|doc-link-audit|Audit and fix broken internal documentation links|New guide pages and deprecation links need systematic checking|Record the scanned source scope and broken targets~Fix verified broken links only~Keep generated dist files out of the PR
R1|heading-audit|Review reference-page heading hierarchy for accessibility|Markdown pages repeat titles and headings without an accessibility audit|Check rendered heading order and navigation~Fix concrete issues with before/after evidence~Do not restyle the whole site
R1|code-copy-audit|Check shell examples for copy-paste correctness|Examples combine server env names and client placeholders|Verify commands with fake endpoints where possible~Label placeholders and shell assumptions clearly~Never execute paid calls as part of the audit
R1|keyboard-audit|Audit documentation keyboard navigation|No accessibility verification is recorded|Check sidebar search code controls and focus visibility~Record browser and reproducible defects~Fix only within the site's existing framework conventions
D2|translation-policy|Design documentation translation ownership|Unmaintained translations can publish stale security instructions|Choose a small initial language set and reviewer process~Define source synchronization and outdated-page notices~Do not bulk-generate translations without review
R1|readme-contract-summary|Complete the concise README response contract summary|README lists endpoints but response fields remain in separate reference pages|Add a short field and enum summary linked to canonical docs~Explain string score versus integer certainty~Keep the README brief and preserve /email deprecation|39
D2|site-metadata|Define configurable documentation canonical URL and sitemap policy|The docs build warns that site is unset|Support preview builds without canonicalizing to the wrong host~Document production URL configuration~Verify generated sitemap and canonical links
"""),
"testing": ("Test infrastructure", "TST", "tests/conftest.py pyproject.toml scripts/check.sh .github/workflows/checks.yml", "tests/roadmap/tooling", "pytest", """
R2|check-script-exit|Test the check script exit contract with fake commands|Fail-fast is implemented but has no shell-level regression check|Run the script with a temporary fake uv executable~Verify failed pytest stops lint and failed lint propagates a nonzero exit~Do not modify a developer shell configuration
R2|assessment-factory|Add a small reusable valid assessment factory|Tests duplicate response dictionaries with inconsistent values|Return complete valid synthetic responses with explicit overrides~Avoid a MagicMock that bypasses response validation~Keep it independent of provider internals
R2|wav-factory|Add a tiny in-memory synthetic WAV fixture factory|Duration tests hand-build WAV data separately|Allow controlled frame count sample rate and channels~Generate data without FFmpeg or Whisper~Document ownership and size bounds
R2|network-guard|Design a test fixture that blocks accidental external network calls|Mocks prevent known calls but new tests can accidentally contact services|Allow TestClient and explicitly local integration transports~Fail unexpected outbound requests with an actionable error~Do not break fake Redis or async tests
R2|credential-guard|Verify unit tests cannot use developer credentials|conftest overrides keys but env/import regressions could expose them|Test with distinctive inherited fake secrets in a subprocess~Assert no upstream call or secret output~Keep user .env untouched
R2|test-env-cleanup|Audit fixture teardown for environment and singleton state|Module caches and environment overrides can cause order dependence|Identify leaked mutations and add scoped cleanup~Demonstrate order-independent affected tests~Avoid a global reset that hides state bugs
R2|integration-markers|Define opt-in markers for real Redis FFmpeg and model checks|Current unit and smoke paths are separate but future tests need clear selection|Register markers and default exclusions with examples~Require explicit opt-in for paid provider checks~Do not skip ordinary unit coverage
R2|redis-container-test|Add an opt-in Redis 7 transaction integration test|fakeredis cannot guarantee every server semantic|Start or connect only to an isolated test instance~Verify TTL and concurrent quota semantics~Clean only namespaced test keys
R2|ffmpeg-fixture-test|Add an opt-in licensed-fixture decode matrix|The smoke script decodes only a generated WAV|Exercise a small documented set of container formats~Record generation commands and avoid private audio~Keep model inference mocked
R2|asgi-body-helper|Extract a reusable chunked ASGI request test helper|One multipart test embeds a custom streaming request inline|Support separate chunks without TestClient coalescing~Preserve disconnect and error visibility~Use it without replacing framework parsing
R2|fake-clock|Add deterministic clock control for timeout tests|Real sleeps would make socket and retry tests slow|Choose narrow injectable clocks or awaitables~Demonstrate cancellation-safe teardown~Do not monkeypatch time globally for all tests
R2|thread-coordination|Provide deterministic helpers for concurrency regressions|Slot and lazy-load races need repeatable coordination|Use events barriers and explicit timeouts~Fail rather than hang on deadlock~Avoid asserting execution order that is not contractual
D2|coverage-baseline|Establish coverage reporting before choosing thresholds|There is no measured branch coverage baseline|Report per-module coverage and uncovered behaviors~Do not gate PRs on an arbitrary percentage initially~Keep generated coverage artifacts out of Git
D2|coverage-gaps|Design changed-code coverage feedback for PRs|Global coverage can hide newly untested failure paths|Choose lightweight tooling and actionable comments~Account for intentional platform-specific branches~Avoid repeated noisy bot comments
D2|property-tests|Evaluate property-based testing for text and filtering boundaries|Hand-written examples miss combinations of Unicode and regex inputs|Select a small invariant set and reproducible seeds~Bound input size and runtime~Add the dependency only with maintainer approval
D2|mutation-pilot|Pilot mutation testing on pure validation code|Coverage alone does not show assertion strength|Choose a small module and a bounded local run~Report useful surviving mutations~Do not add expensive mutation jobs to every PR
D2|pytest-parallel|Evaluate safe parallel test execution|Shared module state may prevent reliable xdist execution|Inventory isolation issues before adding workers~Benchmark actual benefit and memory use~Keep a deterministic serial fallback
D2|python-matrix|Define a supported Python-version test matrix|requires-python has no upper bound while CI uses one version|Verify dependency wheel availability for proposed versions~Define support rather than implying all future versions work~Keep resource-heavy combinations bounded
D2|platform-matrix|Design lightweight cross-platform contributor checks|Only Ubuntu CI verifies Python while contributors use macOS and Windows|Select core mocked tests that need no model tooling~Budget job count and explain platform exclusions~Do not claim container parity from unit tests
D2|ci-artifacts|Define useful sanitized failure artifacts in CI|Failures may be hard to diagnose without reproducible output|Collect junit or limited logs with retention bounds~Exclude env dumps tokens and private fixtures~Keep artifacts optional on successful runs
"""),
"architecture": ("Architecture and service boundaries", "ARC", "app/api/analyze.py app/main.py app/config.py app/services/auth.py tests/test_security.py", "docs/decisions/architecture", "decision", """
D3|route-boundaries|Plan independent route modules without changing contracts|One analyze.py file concentrates text audio and socket edits|Map imports and shared orchestration first~Propose a behavior-preserving migration with characterization tests~Keep endpoint paths and error envelopes unchanged
D3|application-factory|Design an application factory for isolated configuration|The global app imports module-level configuration|Define create_app inputs lifespan and dependency ownership~Keep the existing ASGI entrypoint compatible~Demonstrate multiple isolated test apps
D3|assessment-interface|Define a narrow assessment service interface|Routes import the concrete assessment function directly|Specify validated return type and domain errors~Keep provider SDK types outside route contracts~Avoid a plugin framework before multiple implementations exist
D3|transcription-interface|Define a narrow transcription service interface|Routes and model loading are coupled through module globals|Specify inputs limits and error types~Allow test fakes without importing Whisper~Preserve bounded execution semantics
D3|quota-interface|Define quota decisions separately from HTTP exceptions|Auth combines Redis decisions and transport errors|Represent allowed denied and unavailable outcomes explicitly~Map decisions consistently to HTTP and sockets~Preserve atomic shared quotas
D3|auth-interface|Separate credential identification from transport extraction|Middleware dependencies and WebSockets parse credentials separately|Define one parsing contract and transport adapters~Preserve pre-body HTTP rejection~Include adversarial header compatibility tests
D3|audio-orchestrator|Move audio orchestration behind a transport-neutral boundary|analyze_audio lives in the route module and raises HTTPException|Specify domain results errors and cleanup ownership~Keep HTTP and socket adapters thin~Preserve semaphore lifetime under cancellation
D3|model-lifecycle|Define model ownership during startup and shutdown|Lazy singleton and preload behavior share global state|Specify readiness and failure recovery rules~Define resource cleanup where supported~Avoid unloading a model while inference is active
D3|settings-lifecycle|Specify configuration reload versus restart behavior|Most env settings are read at import and tokens persist in connections|Document which settings are immutable per process~Define rotation and rollout expectations~Do not introduce hot reload without a requirement
D3|domain-errors|Define stable domain exceptions at service boundaries|RuntimeError HTTPException and provider errors cross several layers|Inventory current behavior and proposed mappings~Keep sensitive internals out of public messages~Coordinate with global error-envelope design
D3|request-context|Design a minimal internal request context|Identity timing and correlation need consistent propagation|Include only necessary bounded metadata~Keep raw payloads and credentials out of context logs~Avoid framework-global mutable state
D3|blocking-work|Audit blocking work across HTTP and WebSocket paths|FastAPI sync routes and asyncio.to_thread have different execution pools|Map all file Redis provider and inference operations~Identify starvation risks with reproducible local scenarios~Recommend changes from evidence rather than blanket async conversion
D3|multi-user-capacity|Define a fair multi-user capacity model|Audio currently admits one clip per worker|Specify fairness overload and process-level versus shared limits~Benchmark with fake slow services before changing concurrency~Preserve bounded memory and provider spend|20
D3|cancellation-contract|Specify cancellation and ownership for background thread work|Disconnecting a caller does not stop a running thread|Define slot release temp-file lifetime and provider completion behavior~Identify work that needs process isolation~Test ownership rather than pretending cancellation is immediate
D3|compatibility-tests|Design characterization tests before splitting service modules|Refactoring import targets can silently weaken mocks|Inventory endpoint and error contracts from current main~Require behavior parity before moving logic~Separate code movement from new features
D2|module-map|Write a dependency map identifying shared-file hotspots|Contributor independence needs known boundaries|Show current imports and likely conflict locations~Recommend small extraction candidates with tradeoffs~Do not refactor as part of the map
D3|data-flow-types|Evaluate internal typed models for transcript and assessment flow|Raw strings carry different sensitivity and lifecycle meanings|Define only types that prevent demonstrated mistakes~Keep serialization at boundaries~Avoid wrapping every primitive without benefit
D3|extension-policy|Define how optional integrations should enter the repository|New clients providers and cloud adapters can expand core dependencies|Set ownership test and support requirements~Prefer optional packages where justified~Keep the default local test path simple
D2|deprecation-policy|Write an ADR for removing legacy API features|The email alias is deprecated without a removal schedule|Define notification evidence and migration prerequisites~Do not set an arbitrary removal date without users' input~Cover docs examples and client compatibility
D3|dependency-direction|Define enforceable dependency direction after modularization|No automated check prevents route/service cycles|Propose package boundaries and a minimal checking approach~Apply only after the architecture is agreed~Avoid making all tests depend on an unmerged refactor
"""),
"deployment": ("Deployment and delivery", "DEP", "Dockerfile compose.yaml scripts/serve.sh .github/workflows/checks.yml docs/src/content/docs/guides/deployment.md", "docs/decisions/deployment", "decision", """
D3|ecs-reference|Design a minimal ECS deployment reference|The repository has Compose but no ECS infrastructure artifacts|Specify ECR ALB task service and Redis boundaries~Choose Terraform or CDK once rather than maintaining both~Estimate cost categories without inventing prices
D3|ecs-storage|Design writable storage for a read-only ECS task|The API requires temp files and a model cache|Specify /tmp and cache mount ownership and size~Compare ephemeral storage EFS and prebuilt model artifacts~Verify non-root UID 10001 behavior
D3|ecs-secrets|Specify ECS task execution-role secret injection|ECS injects secrets using the execution role rather than ordinary app reads|Document least-privilege Secrets Manager and KMS permissions~Separate execution role from task role~Avoid storing secret values in IaC state where possible
D3|ecs-redis|Design a managed Redis connection example|Managed cache choices differ in TLS auth and cost|Select supported Redis or Valkey compatibility settings~Document rediss URL authentication and network rules~Test against an isolated cache before production guidance
D3|ecs-health|Define ECS ALB and app health settings together|Model preloading can exceed default startup grace periods|Separate process liveness Redis readiness and model warmup~Align target checks grace periods and rollback behavior~Do not make live DeepSeek calls in probes
D3|ecs-network|Design a cost-conscious ECS network layout|Private tasks need outbound DeepSeek and model access|Compare NAT gateways endpoints and availability tradeoffs~Keep ALB public and tasks/cache private~Explain that two AZs do not require two tasks but HA does
D3|ecs-autoscale|Design measured ECS autoscaling for text and audio|CPU utilization alone may not reflect serialized audio capacity|Select metrics after collecting a baseline~Set max capacity and cost controls~Account for model startup delay
D3|ecs-draining|Specify safe ECS rolling deployment and connection draining|Audio and WebSockets may outlive default shutdown intervals|Align target deregistration process grace and client retry behavior~Test SIGTERM with in-flight fake inference~Avoid promising uninterrupted work on forced termination
D3|ecs-release|Design immutable ECR-to-ECS deployments using GitHub OIDC|Current CI builds images but does not deploy AWS infrastructure|Define repository branch and IAM trust conditions~Promote the same image digest through environments~Avoid long-lived AWS keys
D2|image-scanning|Evaluate container vulnerability scanning in CI|The image includes a large native audio dependency stack|Choose a tool and severity/exception policy~Record base-image and application findings separately~Avoid silently failing open on scanner errors
D2|image-sbom|Design an SBOM artifact for release images|Operators need dependency provenance for native and Python layers|Choose a standard SBOM format and generation point~Associate it with immutable image digest~Keep credentials and source content out of artifacts
D3|image-signing|Evaluate image signing and deployment verification|Commit tags alone do not prove artifact provenance|Define signing identity and verification policy~Prefer short-lived OIDC-backed signing~Document recovery and trust-root changes
D2|base-image-updates|Define a scheduled base-image refresh policy|Frozen Python dependencies do not refresh OS security packages|Choose rebuild cadence and smoke-check requirements~Record base image digest changes~Avoid claiming a fixed tag is immutable
D2|amd64-arm64|Design a multi-architecture build support matrix|Local verification and hosted CI use different CPU architectures|Verify dependency wheels and FFmpeg smoke on both targets~Publish supported platforms explicitly~Account for cross-build emulation costs
D2|model-prewarm|Compare startup download with prewarmed model delivery|Every replacement task may download weights without shared cache|Measure image size startup latency and update ownership~Preserve upstream model license and integrity checks~Do not embed provider secrets in model artifacts
D2|docker-logs|Add bounded Docker log rotation guidance|Compose restart policies do not bound host log growth|Specify log driver size and file limits~Document how it interacts with centralized collection~Verify Compose configuration locally
D2|compose-upgrades|Write a tested Compose upgrade and rollback procedure|Existing docs advise keeping an image but lack an executable rehearsal|Use immutable tags and health checks on a disposable stack~Preserve model cache and explain quota resets~Do not delete production volumes by default
D3|egress-policy|Design outbound access controls compatible with model downloads|The API needs DeepSeek and initial weight access but not arbitrary destinations|Inventory required endpoints and DNS/TLS behavior~Compare proxy and network-level enforcement~Avoid fragile static IP allowlists without maintenance
D2|cost-model|Build a documented capacity and cost worksheet|Choosing ECS resources without measurements can overprovision|Separate idle infrastructure provider usage and inference compute~Use user-supplied current prices and measured throughput~Do not claim EKS is cheaper by default
D2|restore-drill|Define a disposable recovery drill for deployment artifacts|The cache is reproducible and Redis quotas are ephemeral but credentials matter|List rebuildable versus protected state~Test restoring config and image references without real secrets~Document expected quota and warmup behavior
"""),
"jobs": ("Asynchronous audio proposals", "JOB", "app/api/analyze.py app/services/transcription.py docs/src/content/docs/guides/deployment.md", "docs/decisions/jobs", "decision", """
D3|async-adr|Decide whether asynchronous audio belongs in this repository|The current API is synchronous and a separate EKS lab was discussed|Compare a separate gateway/worker project with core API expansion~Document ownership compatibility and cost~Approve scope before implementation tickets are promoted
D3|job-state-machine|Specify job states and legal transitions|Async work needs more than queued/complete booleans|Define queued processing succeeded failed cancelled and expired transitions~Specify terminal-state immutability and attempt counters~Use the approved async architecture
D3|job-auth|Specify job ownership and authorization|Backend tokens alone do not identify extension users|Derive ownership from verified identity and tenant scope~Prevent enumeration and cross-user access~Decide identity integration before endpoint work
D3|job-create-contract|Design idempotent job creation semantics|Client retries could create duplicate paid jobs|Define idempotency key scope payload mismatch and expiry~Specify response codes and duplicate behavior~Avoid storing raw text in deduplication keys
D3|upload-contract|Design bounded direct-to-S3 audio upload authorization|Presigned uploads need limits and ownership rules|Compare POST policies and PUT URLs including size enforcement~Use server-generated object keys and short expiry~Do not accept arbitrary client bucket or key values
D3|upload-finalization|Design safe upload verification before enqueueing|Clients can claim an upload completed when it did not|Verify object ownership existence size and immutable version identity~Define stale and replaced-object handling~Do not trust declared content type as audio validation
D3|queue-envelope|Specify a versioned content-minimal queue message|SQS messages should reference jobs rather than contain private recordings|Define job ID version and required metadata~Validate unknown versions and poison messages~Avoid embedding tokens or presigned URLs
D3|enqueue-consistency|Design reliable persistence-to-queue handoff|Saving a job and sending SQS are not one transaction|Evaluate an outbox or reconciliation approach~Specify duplicate and lost-send recovery~Do not rely on an optimistic two-call sequence
D3|job-lease|Specify atomic job claiming and processing leases|At-least-once delivery can run duplicate workers|Use conditional state transitions with lease expiry~Define contention and owner checks~Separate lease recovery from successful terminal states
D3|queue-visibility|Design SQS visibility extension for long inference|Processing may outlast the initial visibility timeout|Specify heartbeat cadence total processing ceiling and extension failure behavior~Coordinate with worker shutdown~Do not promise exactly-once model calls
D3|job-retries|Specify retry classification and per-job budgets|Unbounded retries can amplify provider costs|Define transient permanent and malformed-job categories~Honor Retry-After within an overall attempt/deadline budget~Coordinate API SDK and queue retries
D3|dead-letter|Design dead-letter inspection and safe redrive|Failed jobs need diagnosis without exposing input|Define redrive eligibility and terminal-state reconciliation~Keep payloads and credentials out of dashboards~Prevent replay of already completed jobs
D3|job-cancel|Define cancellation semantics for queued and active jobs|Running transcription cannot be cancelled by deleting an SQS message|Distinguish cancel requested from actually stopped~Define provider billing and result handling after cancellation~Use process isolation only if justified
D3|job-results|Design bounded result persistence and expiry|Job results may include sensitive summaries|Specify access controls TTL size limits and deletion behavior~Explain that DynamoDB TTL deletion is asynchronous~Avoid claiming immediate erasure
D3|object-retention|Define uploaded-object retention and cleanup guarantees|S3 lifecycle expiry alone is not immediate cleanup|Specify success failure abandoned-upload and versioned-object paths~Use lifecycle as a backstop with clear timing caveats~Keep retention policy visible to users
D3|worker-shutdown|Specify worker drain behavior under SIGTERM|Autoscaling and deployment can interrupt active leases|Stop accepting new messages and handle active visibility safely~Define grace limits and resumability~Test with fake slow inference
D3|queue-autoscale|Design bounded queue-based worker scaling|Queue length alone can overwhelm downstream API quotas|Include queue age processing duration and provider capacity~Set minimum maximum and cooldown policy~Keep ECS as the production default unless architecture changes
D3|job-polling|Define polling responses with bounded client load|Many clients polling every second can dominate API traffic|Specify ownership checks Retry-After and conditional reads~Keep terminal responses stable~Document expiry versus not-found behavior
D3|job-notifications|Evaluate signed completion webhooks versus polling|Callbacks introduce SSRF retries and signature-management risks|Define allowed destinations authentication replay protection and delivery budgets~Do not send callbacks to arbitrary unvalidated URLs~Keep polling as a supported fallback
D3|job-fault-matrix|Design crash and replay tests for the async lifecycle|Happy-path tests cannot establish durable job correctness|Cover crash before enqueue after claim after provider and before acknowledgement~Assert bounded duplicate effects and eventual terminal state~Use local fakes before paid cloud experiments
"""),
}
